# Define variables
@Host = localhost
@Port = 7000


### Getting system-server-info
GET http://{{Host}}:{{Port}}/sys-server-info?sysInfo=true


### Download file from server
GET http://{{Host}}:{{Port}}/download-file?filePath=tests/rest.http



### Upload File To Server
POST http://{{Host}}:{{Port}}/admin/upload
Content-Type: multipart/form-data

Content-Disposition: form-data; name="file"; filename="index.htm"
Content-Type: application/pdf

# The file content is read from the local file system at the specified path.
< ./boost_1_85_0/index.htm



###


###
GET http://{{Host}}:{{Port}}/admin/testasync



###
GET http://{{Host}}:{{Port}}/admin/home