# Define variables
@Host = localhost
@Port = 7000


### Getting system-server-info
GET http://{{Host}}:{{Port}}/sys-server-info?sysInfo=true


### Render any html page
GET http://{{Host}}:{{Port}}/render-html?filePath=templates/home.html


### Download file from server
GET http://{{Host}}:{{Port}}/download-file?filePath=tests/rest.http


### Upload File To Server
POST http://{{Host}}:{{Port}}/upload-file
Content-Type: multipart/form-data
Content-Disposition: form-data; name="file"; filename="rest.py"
Content-Type: application/pdf
# The file content is read from the local file system at the specified path.
< ./tests/rest.py


### Authenticate
POST http://{{Host}}:{{Port}}/authenticate
Content-Type: application/json
{
    "username": "user1",
    "password": "password1"
}



